version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: together-done-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'

  redis:
    image: redis:latest
    container_name: together-done-redis
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
volumes:
  postgres_data:
